<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\Client;
use App\Models\Resource;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActivitySeeder extends Seeder
{

    public function run()
    {
        $activities = [
            [
                'ticket_detail' => 'Sample Ticket Detail 2',
                'activity_start_date' => '2024-06-25T13:00',
                'location' => 'Sample Location 2',
                'activity_description' => 'Sample Activity Description 2',
                'tech_country_id' => 2,
                'tech_city' => 'pakistan',
                'resource_id' => 1,
                'duration' => 10,
                'duration_cust' => 10,
                'tech_service_type' => 'Hourly',
                'tech_rates' => '150.00',
                'tech_currency_id' => 2,
                'client_id' => 1,
                'project_id' => 1,
                'po_number' => 'PO654321',
                'customer_service_type' => 'Hourly Rate',
                'customer_rates' => '50.00',
                'customer_currency_id' => 2,
                'tech_invoice' => null,
                'customer_invoice' => null,
                'tech_invoice_payment_status' => null,
                'customer_invoice_payment_status' => null,
                'email_screenshot' => 'sample_screenshot2.jpg',
                'activity_status' => 'pending',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'default_time' =>  Carbon::now()->format('Y-m-d\TH:i'),
                'pakistani_time' => Carbon::now()->format('Y-m-d\TH:i'),
                'start_date_time' =>  Carbon::now(),
                'end_date_time' =>  Carbon::now(),
                'total_tech_payments' =>  '100',
                'total_customer_payments' =>  '120',
                'time_difference' =>  '2 minutes',
            ],
            [
                'ticket_detail' => 'Sample Ticket Detail 3',
                'activity_start_date' => '2024-06-25T13:00',
                'location' => 'Sample Location 2',
                'activity_description' => 'Sample Activity Description 2',
                'tech_country_id' => 2,
                'tech_city' => 'pakistan',
                'resource_id' => 1,
                'tech_service_type' => 'Hourly',
                'tech_rates' => '150.00',
                'tech_currency_id' => 2,
                'duration' => 10,
                'duration_cust' => 10,
                'client_id' => 2,
                'project_id' => 1,
                'po_number' => 'PO654321',
                'customer_service_type' => 'Hourly Rate',
                'customer_rates' => '50.00',
                'customer_currency_id' => 2,
                'tech_invoice' => null,
                'customer_invoice' => null,
                'tech_invoice_payment_status' => null,
                'customer_invoice_payment_status' => null,
                'email_screenshot' => 'sample_screenshot2.jpg',
                'activity_status' => 'confirmed',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'default_time' =>  Carbon::now()->format('Y-m-d\TH:i'),
                'pakistani_time' => Carbon::now()->format('Y-m-d\TH:i'),
                'start_date_time' =>  Carbon::now(),
                'end_date_time' =>  Carbon::now(),
                'total_tech_payments' =>  '125',
                'total_customer_payments' =>  '215',
                'time_difference' =>  '2 minutes',
            ],
            [
                'ticket_detail' => 'Sample Ticket Detail 4',
                'activity_start_date' => '2024-06-25T13:00',
                'location' => 'Sample Location 2',
                'activity_description' => 'Sample Activity Description 2',
                'tech_country_id' => 2,
                'tech_city' => 'pakistan',
                'resource_id' => 1,
                'tech_service_type' => 'Hourly',
                'tech_rates' => '150.00',
                'tech_currency_id' => 2,
                'duration' => 10,
                'duration_cust' => 10,
                'client_id' => 2,
                'project_id' => 1,
                'po_number' => 'PO654321',
                'customer_service_type' => 'Hourly Rate',
                'customer_rates' => '50.00',
                'customer_currency_id' => 2,
                'tech_invoice' => null,
                'customer_invoice' => null,
                'tech_invoice_payment_status' => null,
                'customer_invoice_payment_status' => null,
                'email_screenshot' => 'sample_screenshot2.jpg',
                'activity_status' => 'closed',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'default_time' =>  Carbon::now()->format('Y-m-d\TH:i'),
                'pakistani_time' => Carbon::now()->format('Y-m-d\TH:i'),
                'start_date_time' =>  Carbon::now(),
                'end_date_time' =>  Carbon::now(),
                'total_tech_payments' =>  '125',
                'total_customer_payments' =>  '235',
                'time_difference' =>  '2 minutes',
            ],
            [
                'ticket_detail' => 'Sample Ticket Detail 5',
                'activity_start_date' => '2024-06-25T13:00',
                'location' => 'Sample Location 2',
                'activity_description' => 'Sample Activity Description 2',
                'tech_country_id' => 2,
                'tech_city' => 'pakistan',
                'resource_id' => 1,
                'tech_service_type' => 'Hourly',
                'tech_rates' => '150.00',
                'tech_currency_id' => 2,
                'client_id' => 2,
                'project_id' => 1,
                'duration' => 10,
                'duration_cust' => 10,
                'po_number' => 'PO654321',
                'customer_service_type' => 'Hourly Rate',
                'customer_rates' => '50.00',
                'customer_currency_id' => 2,
                'tech_invoice' => null,
                'customer_invoice' => null,
                'tech_invoice_payment_status' => null,
                'customer_invoice_payment_status' => null,
                'email_screenshot' => 'sample_screenshot2.jpg',
                'activity_status' => 'approved',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'default_time' =>  Carbon::now()->format('Y-m-d\TH:i'),
                'pakistani_time' => Carbon::now()->format('Y-m-d\TH:i'),
                'start_date_time' =>  Carbon::now(),
                'end_date_time' =>  Carbon::now(),
                'total_tech_payments' =>  '155',
                'total_customer_payments' =>  '165',
                'time_difference' =>  '2 minutes',
            ],
        ];

        DB::table('activities')->insert($activities);
    }
}
