<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CurrencySeeder extends Seeder
{
   
    public function run()
    {
        $currencies = [
            ['code' => 'AFN', 'symbol' => '؋'],
            ['code' => 'ALL', 'symbol' => 'Lek'],
            ['code' => 'DZD', 'symbol' => 'د.ج'],
            ['code' => 'AOA', 'symbol' => 'Kz'],
            ['code' => 'XCD', 'symbol' => '$'],
            ['code' => 'ARS', 'symbol' => '$'],
            ['code' => 'AMD', 'symbol' => '֏'],
            ['code' => 'AWG', 'symbol' => 'ƒ'],
            ['code' => 'AUD', 'symbol' => 'A$'],
            ['code' => 'AZN', 'symbol' => '₼'],
            ['code' => 'BHD', 'symbol' => '.د.ب'],
            ['code' => 'BDT', 'symbol' => '৳'],
            ['code' => 'BBD', 'symbol' => '$'],
            ['code' => 'BYN', 'symbol' => 'Br'],
            ['code' => 'BZD', 'symbol' => '$'],
            ['code' => 'XOF', 'symbol' => 'Fr'],
            ['code' => 'BMD', 'symbol' => '$'],
            ['code' => 'BTN', 'symbol' => 'Nu.'],
            ['code' => 'BOB', 'symbol' => '$b'],
            ['code' => 'BOV', 'symbol' => 'Bs'],
            ['code' => 'BRL', 'symbol' => 'R$'],
            ['code' => 'BSD', 'symbol' => '$'],
            ['code' => 'BND', 'symbol' => '$'],
            ['code' => 'BGN', 'symbol' => 'лв'],
            ['code' => 'BIF', 'symbol' => 'FBu'],
            ['code' => 'KHR', 'symbol' => '៛'],
            ['code' => 'CAD', 'symbol' => '$'],
            ['code' => 'CVE', 'symbol' => '$'],
            ['code' => 'KYD', 'symbol' => '$'],
            ['code' => 'XAF', 'symbol' => 'FCFA'],
            ['code' => 'XPF', 'symbol' => '₣'],
            ['code' => 'CLP', 'symbol' => '$'],
            ['code' => 'CNY', 'symbol' => '¥'],
            ['code' => 'COP', 'symbol' => '$'],
            ['code' => 'KMF', 'symbol' => 'CF'],
            ['code' => 'CDF', 'symbol' => 'FC'],
            ['code' => 'CRC', 'symbol' => '₡'],
            ['code' => 'HRK', 'symbol' => 'kn'],
            ['code' => 'CUP', 'symbol' => '₱'],
            ['code' => 'CUC', 'symbol' => '$'],
            ['code' => 'CZK', 'symbol' => 'Kč'],
            ['code' => 'DKK', 'symbol' => 'kr'],
            ['code' => 'DJF', 'symbol' => 'Fdj'],
            ['code' => 'DOP', 'symbol' => 'RD$'],
            ['code' => 'EGP', 'symbol' => '£'],
            ['code' => 'ERN', 'symbol' => 'Nfk'],
            ['code' => 'ETB', 'symbol' => 'Br'],
            ['code' => 'EUR', 'symbol' => '€'],
            ['code' => 'FJD', 'symbol' => '$'],
            ['code' => 'FKP', 'symbol' => '£'],
            ['code' => 'FOK', 'symbol' => 'kr'],
            ['code' => 'GMD', 'symbol' => 'D'],
            ['code' => 'GEL', 'symbol' => '₾'],
            ['code' => 'GHS', 'symbol' => '₵'],
            ['code' => 'GIP', 'symbol' => '£'],
            ['code' => 'GTQ', 'symbol' => 'Q'],
            ['code' => 'GNF', 'symbol' => 'Fr'],
            ['code' => 'GYD', 'symbol' => '$'],
            ['code' => 'HTG', 'symbol' => 'G'],
            ['code' => 'HNL', 'symbol' => 'L'],
            ['code' => 'HKD', 'symbol' => '$'],
            ['code' => 'HUF', 'symbol' => 'Ft'],
            ['code' => 'ISK', 'symbol' => 'kr'],
            ['code' => 'INR', 'symbol' => '₹'],
            ['code' => 'IDR', 'symbol' => 'Rp'],
            ['code' => 'IRR', 'symbol' => '﷼'],
            ['code' => 'IQD', 'symbol' => 'ع.د'],
            ['code' => 'ILS', 'symbol' => '₪'],
            ['code' => 'JMD', 'symbol' => '$'],
            ['code' => 'JPY', 'symbol' => '¥'],
            ['code' => 'JOD', 'symbol' => 'د.أ'],
            ['code' => 'KZT', 'symbol' => '₸'],
            ['code' => 'KES', 'symbol' => 'KSh'],
            ['code' => 'KWD', 'symbol' => 'د.ك'],
            ['code' => 'KGS', 'symbol' => 'с'],
            ['code' => 'LAK', 'symbol' => '₭'],
            ['code' => 'LBP', 'symbol' => 'ل.ل'],
            ['code' => 'LSL', 'symbol' => 'L'],
            ['code' => 'LRD', 'symbol' => '$'],
            ['code' => 'LYD', 'symbol' => 'ل.د'],
            ['code' => 'MOP', 'symbol' => 'MOP$'],
            ['code' => 'MKD', 'symbol' => 'ден'],
            ['code' => 'MGA', 'symbol' => 'Ar'],
            ['code' => 'MWK', 'symbol' => 'MK'],
            ['code' => 'MYR', 'symbol' => 'RM'],
            ['code' => 'MVR', 'symbol' => 'Rf'],
            ['code' => 'MRU', 'symbol' => 'UM'],
            ['code' => 'MUR', 'symbol' => '₨'],
            ['code' => 'MXN', 'symbol' => '$'],
            ['code' => 'MXV', 'symbol' => '$'],
            ['code' => 'MDL', 'symbol' => 'lei'],
            ['code' => 'MNT', 'symbol' => '₮'],
            ['code' => 'MAD', 'symbol' => 'د.م.'],
            ['code' => 'MZN', 'symbol' => 'MT'],
            ['code' => 'MMK', 'symbol' => 'K'],
            ['code' => 'NAD', 'symbol' => '$'],
            ['code' => 'NPR', 'symbol' => '₨'],
            ['code' => 'NGN', 'symbol' => '₦'],
            ['code' => 'NIO', 'symbol' => 'C$'],
            ['code' => 'NOK', 'symbol' => 'kr'],
            ['code' => 'OMR', 'symbol' => 'ر.ع.'],
            ['code' => 'PKR', 'symbol' => '₨'],
            ['code' => 'PAB', 'symbol' => 'B/.'],
            ['code' => 'PGK', 'symbol' => 'K'],
            ['code' => 'PYG', 'symbol' => '₲'],
            ['code' => 'PEN', 'symbol' => 'S/'],
            ['code' => 'PHP', 'symbol' => '₱'],
            ['code' => 'PLN', 'symbol' => 'zł'],
            ['code' => 'QAR', 'symbol' => 'ر.ق'],
            ['code' => 'RON', 'symbol' => 'lei'],
            ['code' => 'RUB', 'symbol' => '₽'],
            ['code' => 'RWF', 'symbol' => 'FRw'],
            ['code' => 'SHP', 'symbol' => '£'],
            ['code' => 'WST', 'symbol' => 'T'],
            ['code' => 'STN', 'symbol' => 'Db'],
            ['code' => 'SAR', 'symbol' => 'ر.س'],
            ['code' => 'RSD', 'symbol' => 'дин.'],
            ['code' => 'SCR', 'symbol' => '₨'],
            ['code' => 'SLL', 'symbol' => 'Le'],
            ['code' => 'SGD', 'symbol' => '$'],
            ['code' => 'SBD', 'symbol' => '$'],
            ['code' => 'SOS', 'symbol' => 'S'],
            ['code' => 'ZAR', 'symbol' => 'R'],
            ['code' => 'KRW', 'symbol' => '₩'],
            ['code' => 'SSP', 'symbol' => '£'],
            ['code' => 'LKR', 'symbol' => '₨'],
            ['code' => 'SPL', 'symbol' => 'SPL'],
            ['code' => 'SRD', 'symbol' => '$'],
            ['code' => 'SZL', 'symbol' => 'E'],
            ['code' => 'SEK', 'symbol' => 'kr'],
            ['code' => 'CHF', 'symbol' => 'CHF'],
            ['code' => 'SYP', 'symbol' => '£'],
            ['code' => 'TJS', 'symbol' => 'SM'],
            ['code' => 'TZS', 'symbol' => 'TSh'],
            ['code' => 'THB', 'symbol' => '฿'],
            ['code' => 'TOP', 'symbol' => 'T$'],
            ['code' => 'TTD', 'symbol' => '$'],
            ['code' => 'TND', 'symbol' => 'د.ت'],
            ['code' => 'TRY', 'symbol' => '₺'],
            ['code' => 'TMT', 'symbol' => 'm'],
            ['code' => 'UGX', 'symbol' => 'USh'],
            ['code' => 'UAH', 'symbol' => '₴'],
            ['code' => 'AED', 'symbol' => 'د.إ'],
            ['code' => 'USD', 'symbol' => '$'],
            ['code' => 'UYU', 'symbol' => '$U'],
            ['code' => 'UZS', 'symbol' => 'лв'],
            ['code' => 'VUV', 'symbol' => 'Vt'],
            ['code' => 'VEF', 'symbol' => 'Bs'],
            ['code' => 'VND', 'symbol' => '₫'],
            ['code' => 'YER', 'symbol' => 'ر.ي'],
            ['code' => 'ZMW', 'symbol' => 'ZK'],
            ['code' => 'ZWL', 'symbol' => '$'],
        ];
        DB::table('currencies')->insert(array_map(function ($currency) {
            return array_merge($currency, [
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }, $currencies));
    }
}
